name: CI

on:

  schedule:
    - cron: "0 0 * * *"

  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: git version
        run: git --version